name: build-and-test.yml
on: [push]
jobs:
  build-and-test-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-go@v2
      - run: git clone https://github.com/magefile/mage
      - run: pushd mage; go run bootstrap.go; 
